* Vi gør det forkert
Ifølge §59 i "Bekendtgørelse af lov om ophavsret" fremgår det at:

#+BEGIN_QUOTE
Ophavsretten til et edb-program, der er frembragt af en arbejdstager
under udførelsen af dennes arbejde eller efter arbejdsgiverens
anvisninger, overgår til arbejdsgiveren. -- https://www.retsinformation.dk/eli/lta/2014/1144
#+END_QUOTE

Det gældre formentlig også andre værker udover edb-programmer.

Jeg er lige nu i en proces om at få lov til at udgive frit materiale, udarbejdet i min fritid, undre en fri licens.

Det giver ingen mening, frihed burde være standard.

Dette er ikke min arbejdsgiverens skyld, det falder 100% tilbage på politikerne, at jeg skal tigge om frihed.

Dette er desværre ikke et enestående tilfælde. Jeg er fortiden ved at
læse en rigtig god bog "Ledense på afvejde"[1](lpa) som beskriver den
fejlslagne ledelse og styrring af landet, som er foregået side indførelsen af "new public management" og DJØF'iseringen af det offentlige.
Jeg vil dog mene at det har stået på længere. Det foregik også da jeg var barn, hvis jeg skal tro mine forældre.

Nå men nu skal det jo ikke kun være galle det hele. Jeg har arbejdet
på et af de projekter som beskrives i lpa. Internt kaldet ICE(Jeg
mener det stod for inddrivelses center for ejendomme), eksternt kendt
som "det nye ejendomsvurderings system".Jeg synes ikke de rammer
kritikken helt, men det kan vi altid tage en sank om. Det jeg gerne
vil fremhæve er software project management.

Lad os en gang for alle slå fast at flere mellemledere, og midlertidlige konsulenter, på et projekt ikke betyder hurtigere levering.

Vi skal have fagfolk og reelle interessenter på banen.


[1] Peter Harder, Jep Loft og Gads forlag A/S, 2021
